spring.application.name=labo2_Ncapas

spring.datasource.url=jdbc:postgresql://localhost:5432/police_station
spring.datasource.username=postgres
spring.datasource.password=greninja1207
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
